"use client";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { returnSaleItemsAction } from "@/lib/sales/actions";
import { formatFcfaAbsolute } from "@/lib/utils/format";
import type { Sale } from "@/types/sales";
import type { AuthResult } from "@/types";
export function PartialReturnSaleButton({sale}:{sale:Sale}) { const [open,setOpen]=useState(false); const [quantities,setQuantities]=useState<Record<string,number>>({}); const [state,action,pending]=useActionState(returnSaleItemsAction,{error:null} as AuthResult); const items=sale.items.flatMap(i=>quantities[i.id]>0?[{sale_item_id:i.id,quantity:quantities[i.id]}]:[]); return <><Button type="button" variant="outline" onClick={()=>setOpen(true)}>Retour / avoir</Button><Dialog open={open} title="Retour partiel" onClose={()=>setOpen(false)}><form action={action} className="flex flex-col gap-3"><input type="hidden" name="saleId" value={sale.id}/><input type="hidden" name="items" value={JSON.stringify(items)}/><p className="text-sm text-muted-foreground">Choisissez les quantités retournées. Le stock et l’avoir seront mis à jour automatiquement.</p>{sale.items.map(item=><label key={item.id} className="flex items-center justify-between gap-3 text-sm"><span>{item.productName}<span className="block text-xs text-muted-foreground">Vendu : {item.quantity} · {formatFcfaAbsolute(item.unitPrice)}</span></span><input className="h-10 w-20 rounded border border-border px-2" type="number" min="0" max={item.quantity} step="0.001" value={quantities[item.id] ?? 0} onChange={e=>setQuantities({...quantities,[item.id]:Number(e.target.value)||0})}/></label>)}{state.error?<p className="text-sm text-danger">{state.error}</p>:null}<div className="mt-2 flex gap-2"><Button type="submit" loading={pending} disabled={items.length===0}>Valider le retour</Button><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annuler</Button></div></form></Dialog></>; }
